// front/src/component/SquareImage.tsx
import React from 'react';

import './style/style.css';

import { getServerUrl } from "../ServerInformation";
let url = getServerUrl();

interface Props { className: string, imageName: string | null, size: number, alt: string, alternateImage: any };
interface State { loadedUrl: any | null };

class SquareImage extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);
        this.state = { loadedUrl: null };

        const imageName = this.props.imageName === undefined ? null : this.props.imageName;
        if (imageName !== null) this._loadImage();
    }

    componentDidUpdate(prevProps : Props) {
      if (prevProps.imageName !== this.props.imageName) {
        const imageName = this.props.imageName === undefined ? null : this.props.imageName;
        if (imageName !== null) this._loadImage();
        this._loadImage();
      }
    }

    _loadImage() {
        const request = async() => {
            const response = await fetch(url + '/files/' + this.props.imageName);
            if (response.status === 404) {
                console.error("file " + this.props.imageName + " could not be found on server");
                return;
            }
            if (response.status === 500) {
                console.error("Internal server error: " + response)
                return;
            }

            response.blob().then(blob => {
                let url = window.URL.createObjectURL(blob);
                this.setState({ loadedUrl: url });
            });
        };
        request();
    }

    render() {
        const { className, size, alt, alternateImage } = this.props;
        const { loadedUrl } = this.state;

        if (loadedUrl !== null){
            return <img className={className} height={size} width={size} src={loadedUrl} alt={alt}/>;
        } else {
            return <img className={className} height={size} width={size} src={alternateImage} alt="Nothing"/>;
        }
    }
}



export default SquareImage;

// front-vue/src/components/SquareImage.vue
<script setup lang="ts">
import { ref, watchEffect } from "vue";
import { make_authorized_request } from "./helpers/make_request";

const props = defineProps<{
  imageName: string | null;
  size: number;
  alternateImage: string;
  withTopRound: boolean;
}>();

const emit = defineEmits(["image-loaded"]);

const source = ref(props.alternateImage);

watchEffect(() => {
  if (props.imageName !== null && props.imageName !== "") {
    const fetchImage = async () => {
      const response = await make_authorized_request(`/files/${props.imageName}`);
      if (response !== null) {
        const blob = await response.blob();
        source.value = window.URL.createObjectURL(blob);
        emit("image-loaded", source.value);
      }
    };
    fetchImage();
  }

  source.value = props.alternateImage;
});
</script>

<template>
  <img
    :height="props.size"
    :width="props.size"
    :src="source"
    alt="Nothing"
    :class="withTopRound ? 'top-round' : ''"
  />
</template>

<style lang="css" scoped>
img {
  object-fit: scale-down;
}

.top-round {
  border-radius: 0.375rem 0.375rem 0 0;
}
</style>
